[package]
name = "s5-wgpu-composite"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
anyrender = "0.12.0"
anyrender_vello = "0.13.0"
blitz-dom = { git = "https://github.com/DioxusLabs/blitz", rev = "1efe22d2524d71ede5b94592204c21f0de644219", default-features = false, features = ["custom-widget"] }
blitz-html = { git = "https://github.com/DioxusLabs/blitz", rev = "1efe22d2524d71ede5b94592204c21f0de644219" }
blitz-paint = { git = "https://github.com/DioxusLabs/blitz", rev = "1efe22d2524d71ede5b94592204c21f0de644219", default-features = false, features = ["custom-widget"] }
blitz-traits = { git = "https://github.com/DioxusLabs/blitz", rev = "1efe22d2524d71ede5b94592204c21f0de644219" }
peniko = "0.6.0"
wgpu = "29"
wgpu_context = "0.8.0"
winit = "0.31.0-beta.2"

[patch.crates-io]
anyrender = { git = "https://github.com/DioxusLabs/anyrender", rev = "dcd219746ff13a5832beab552f3f7f494d1bd84d" }
